[package]
name = "punter-server"
version = "0.1.0"
authors = ["Steven Walter <stevenrwalter@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
bytes = "0.5"
